##Spring Configuration
server:
  port: 8081
spring:
  application:
    name: "crediya-solicitudes"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
  management:
    endpoints:
      web:
        exposure:
          include: "health,prometheus"
    endpoint:
      health:
        probes:
          enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8081"
adapters:
  r2dbc:
    mysql:
      host: localhost
      port: 3306
      database: solicitudes
      username: sa
      password: 5697964c
springdoc:
  info:
    title: API de Solicitudes de CrediYa
    version: 1.0
    description: API para la gestión de usuarios y autenticación del sistema.